#pragma once

#define OPUS_SAMPLE_RATE 	16000
#define OPUS_FRAME_MS 		60	// 60ms
#define OPUS_FRAME_SAMPLES	(OPUS_SAMPLE_RATE * OPUS_FRAME_MS / 1000)
#define VAD_WINDOW_MS		32
#define VAD_WINDOW_SAMPLES	(VAD_WINDOW_MS * OPUS_SAMPLE_RATE / 1000)
#define VAD_PRE_FRAMES		5
#define VAD_POST_FRAMES		1
#define VAD_PRE_SAMPLES		(VAD_PRE_FRAMES * OPUS_SAMPLE_RATE * OPUS_FRAME_MS / 1000)
#define MAX_OPUS_PACKET_SIZE 	(1275 * 3 + 7)